In [48]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class MyData(Dataset):
	def __init__(self): 
		self.x_train = [[i]*(i+1) for i in range(10)]
		self.y_train = [[i] for i in range(10)]
		
	def __len__(self):
		return 10
    
	def __getitem__(self, idx):
		x = torch.FloatTensor(self.x_train[idx])
		y = torch.FloatTensor(self.y_train[idx])
		return x, y

def my_collate_fn(data):
	input = [d[0] for d in data]
	label = [d[1] for d in data]
	padding = torch.nn.utils.rnn.pad_sequence(input, batch_first=True);return padding, label


my_dataset = MyData()
dataloader = DataLoader(my_dataset, collate_fn=my_collate_fn, batch_size=3)
for data in dataloader:
    print(data[0], data[1])

tensor([[0., 0., 0.],
        [1., 1., 0.],
        [2., 2., 2.]]) [tensor([0.]), tensor([1.]), tensor([2.])]
tensor([[3., 3., 3., 3., 0., 0.],
        [4., 4., 4., 4., 4., 0.],
        [5., 5., 5., 5., 5., 5.]]) [tensor([3.]), tensor([4.]), tensor([5.])]
tensor([[6., 6., 6., 6., 6., 6., 6., 0., 0.],
        [7., 7., 7., 7., 7., 7., 7., 7., 0.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8.]]) [tensor([6.]), tensor([7.]), tensor([8.])]
tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]]) [tensor([9.])]
